### ISSUE TITLE
Human workers can have lumber and get stuck unable to return it unless you send it back to a tree.

### ISSUE THREAD

**Issue by MSre-zz** [MNoya/DotaCraft#129]
If you grab a group of workers with some not harvesting lumber, and some gathering lumber, and give them some move commands; you can get workers that have lumber on them but the return ability is gone (replaced with gather)

**Comment by MNoya** [comment]
I kinda intended this behavior because right-clicking trees is still a bit awkward, and considering the 6-visible slot limitation (which only leaves one slot for the Gather/Return button), it's really a trade-off between having the Gather button available while still having resources to deliver, or having the Return button available and use it to keep gathering (losing the ability to Q-gather button directly)
