### ISSUE TITLE
Minimum Attack Range

### ISSUE THREAD

**Issue by MNoya** [MNoya/DotaCraft#137]
Units with 250 Minimum Attack Range:
- Mortar Team
- Demolisher
- Glaive Thrower
- Meat Wagon

Behavior should be:
When a direct attack order is issued with a unit selected to a target below its min range, send one error message (_Target is inside minimum range_)
When the unit tries to attack another below its min range, it should stop its attack and reacquire a valid targetfurther further away.
If there are no valid targets, disable autoattack until there are valid enemies
Flee from air units still applies (we don't have min-range units that have air attacks enabled)

**Comment by dun1007** [comment]
Here are some interesting facts about minimum range mechanics on WC3:
- The minimum range is checked during wind-up rather than when attack actually fires, so siege units can attack enemy in close vincinity(<250) if they close the gap after wind-up began.
- In such case, the projectile's AoE is target's location when wind-up starts, rather than when projectile fires.

I did not handle this case yet. Perhaps I can use ground target ability to replicate similar behavior
