### ISSUE TITLE
Additional building collision issue, collision isn't centering on odd buildings, could be contributing to that tree thing.

### ISSUE THREAD

**Issue by MSre-zz** [MNoya/DotaCraft#155]
![dotacraft-issue-gif1](https://cloud.githubusercontent.com/assets/15721434/12002119/660fd168-aab4-11e5-8273-1536b690efdd.gif)
![dotacraft-issue-gif2](https://cloud.githubusercontent.com/assets/15721434/12002121/749bd5e2-aab4-11e5-8eae-5c4588f2b66c.gif)

Gfycat links:
http://gfycat.com/PeriodicConfusedConey
http://gfycat.com/GlisteningWindyBinturong

This issue happened while toggling these values:
"ConstructionSize"          "6"
"BlockPathingSize"          "5"
to
"ConstructionSize"          "5"
"BlockPathingSize"          "6"

Still trying to figure out how to have a building block a 6x6 while still being pathable to units in 5x5. I thought these were the values to use.

**Comment by MNoya** [comment]
Yeah that combination is kind of weird, because as far as I know in WC3 buildings only blocked 2x2, 3x3, 4x4 and then 6x6 for Town Hall (because leaving only 1 gridnav to path between a maze can be a bit problematic I think?). I recommend you try calling `dota_gridnav_show 1` in the tools console to see what is going on, because I haven't tested 5x5 obstructions with the current framework, it might be an error in the `:BlockPSO` function that isn't centering the building properly or taking it as a 4x4.

**Comment by MNoya** [comment]
Ok, thinking more about this, it's impossible to do it. The WC3 grid had double the square sizes than the current Dota grid, and it _always_ left at least 1 grid to each side (so a 10x10 pathing and 12x12 construction block in your case). We can not have "half a grid" blocked, so it has to either align the building to the left or to the right.

What you can do instead, is make it block 4x4 pathing and **increase the building Hull radius** with `:SetHullRadius` to a higher value (try something like 160~180)
