### ISSUE TITLE
Each wisp has independent gold gathering time

### ISSUE THREAD

**Issue by michalhalas** [MNoya/DotaCraft#23]
Summary: As far as I recall, in wc3 multiple wisps in same goldmine 'mimic' the timing orcs and humans have when it comes to gathering.

Procedure:
1. Line wisps up as close to gold mine as possible so they enter it almost at once.

Expected result: +10 should appear at a constant pace.

Result: +10 are happening independently, if wisps joins goldmine silmutaneously, you get +10's silmutaneously.

Additional Note: I didnt test for undeads, but might be same case.

**Comment by MNoya** [comment]
Yes currently the modifier is on each builder instead of the mine producing. I felt it made more sense and looked better visually, do you guys think it's worth keeping the original look? The extract rate is exactly the same

**Comment by michalhalas** [comment]
From casual point of view it kinda looks nice, but looking at competitive state and balancing, elfs and undeads will have in theory their first 50 gold extracted faster than human or orcs, it's a minor thing but worth remembering.

**Comment by TideSofDarK** [comment]
You still can change it to mine producing and keep nice each-wisp look, why not?

**Comment by MNoya** [comment]
@nooDy093 I think the first gold "tick" is still registered at the same time than the wc3 version, because what the entangled/haunted gold mine is doing is just counting the builders inside and make its 10-gold think rate faster or slower depending on that. I'll test how much it takes to collect the first 50 gold with 1 wisp vs humans to be sure, but I already took some minutes to make sure the overall extract rate for all races is identical (600 GPM for all races)

**Comment by michalhalas** [comment]
I meant harvesting first 50 gold with all first 5 wisps should be faster than with first 5 peasants.
