### ISSUE TITLE
Far Sight does not provide flying vision ala Wc3

### ISSUE THREAD

**Issue by asperkin** [MNoya/DotaCraft#3]

**Comment by MNoya** [comment]
Indeed I forgot to change it back, it's a problem with the function I was trying out, use a dummy with vision instead of CreateVisibilityNode

[The old version of far_fight](https://github.com/MNoya/DotaCraft/commit/72e9f55e74c52009965feaaa5eab8d19e3cb3fd3#diff-ec4c938ff4c83d9c63beed33e9f10742) works fine
